## linear Algebra

In [1]:
import sys
import numpy as np

In [2]:
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
B = np.full((2,3),5)
B

array([[5, 5, 5],
       [5, 5, 5]])

In [8]:
C = np.array([6,7,8])
C

array([6, 7, 8])

In [6]:
A - B

array([[-4, -3, -2],
       [-1,  0,  1]])

In [7]:
A + B

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
A / B

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [11]:
A * B

array([[ 5, 10, 15],
       [20, 25, 30]])

In [12]:
np.dot(A,C)

array([ 44, 107])

In [13]:
A @ C

array([ 44, 107])

In [14]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
 I =np.identity(3)

In [22]:
D = np.arange(1,10).reshape(3,3)

In [23]:
A @ D

array([[30, 36, 42],
       [66, 81, 96]])

## Prop
    In . An = An
    An . In = An

In [24]:
I @ C

array([6., 7., 8.])

#### Inverse Matrix

In [31]:
E = np.array([[1,2],
        [3,4]])


In [33]:
np.linalg.det(E)

np.float64(-2.0000000000000004)

In [36]:
np.linalg.inv(E)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [46]:
mat = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np.linalg.det(mat)

np.float64(-9.51619735392994e-16)

In [48]:
np.linalg.inv(mat)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [49]:
D @ np.linalg.inv(D)

array([[ 0. ,  1. , -0.5],
       [ 0. ,  2. , -1. ],
       [-4. ,  3. , -1.5]])

In [50]:
np.round( D @ np.linalg.inv(D) )

array([[ 0.,  1., -0.],
       [ 0.,  2., -1.],
       [-4.,  3., -2.]])